#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

for config_file ($HOME/.yadr/zsh/*.zsh) source $config_file


#
# Change profiles on directory change
#
# This is used to switch git credatials automatically.
#
# http://stackoverflow.com/a/8645101/1168639
#
CHPWD_PROFILE='default'
function chpwd_profiles() {
    local -x profile

    zstyle -s ":chpwd:profiles:${PWD}" profile profile || profile='default'
    if (( ${+functions[chpwd_profile_$profile]} )) ; then
        chpwd_profile_${profile}
    fi

    CHPWD_PROFILE="${profile}"
    return 0
}
chpwd_functions=( ${chpwd_functions} chpwd_profiles )

# configuration for profile 'default':
chpwd_profile_default()
{
    [[ ${profile} == ${CHPWD_PROFILE} ]] && return 1
        print "Switching to git profile: default"

        export GIT_AUTHOR_NAME="Siarhei Khilko"
        export GIT_AUTHOR_EMAIL="skhilko@gmail.com"
        export GIT_COMMITTER_NAME="Siarhei Khilko"
        export GIT_COMMITTER_EMAIL="skhilko@gmail.com"
}

# configuration for profile 'personal':
chpwd_profile_personal()
{
    [[ ${profile} == ${CHPWD_PROFILE} ]] && return 1
        print "Switching to git profile: $profile"

        export GIT_AUTHOR_NAME="Siarhei Khilko"
        export GIT_AUTHOR_EMAIL="skhilko@gmail.com"
        export GIT_COMMITTER_NAME="Siarhei Khilko"
        export GIT_COMMITTER_EMAIL="skhilko@gmail.com"
}

# configuration for profile 'work':
chpwd_profile_work()
{
    [[ ${profile} == ${CHPWD_PROFILE} ]] && return 1
        print "Switching to git profile: $profile"

        export GIT_AUTHOR_NAME="Sergey Khilko"
        export GIT_AUTHOR_EMAIL="skhilko@searshc.com"
        export GIT_COMMITTER_NAME="Sergey Khilko"
        export GIT_COMMITTER_EMAIL="skhilko@searshc.com"
}

chpwd_profile_default # run DEFAULT profile automatically

# Change git profile based on subdirectory we're in
zstyle ':chpwd:profiles:/home/skhilko/src/sears(|/|/*)'  profile work
zstyle ':chpwd:profiles:/home/skhilko/src/personal(|/|/*)'   profile personal

